In [ ]:
!pip install keras


In [9]:
!pip install tensorflow

  Using cached tensorflow-2.12.0-cp39-cp39-win_amd64.whl (1.9 kB)
  Using cached tensorflow_intel-2.12.0-cp39-cp39-win_amd64.whl (272.8 MB)
  Using cached grpcio-1.53.0-cp39-cp39-win_amd64.whl (4.0 MB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached tensorboard-2.12.0-py3-none-any.whl (5.6 MB)
  Using cached jax-0.4.8-py3-none-any.whl
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
  Using cached ml_dtypes-0.0.4-cp39-cp39-win_amd64.whl (97 kB)
  Using cached google_auth-2.17.0-py2.py3-none-any.whl (178 kB)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)


In [16]:
import numpy as np
from numpy import loadtxt 
import keras 
from keras.models import Sequential
from keras.layers import Dense

In [18]:
dataset=loadtxt('E:/Full Stack Data Scientist Bootcamp/datasets/datasets-20221208T145556Z-001/datasets/pima-indians-diabetes.csv',delimiter=',',)


In [22]:
print(dataset)

[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]


In [25]:
x=dataset[:,0:8]
y=dataset[:,8:]
print(x)
print(y)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.

In [28]:
import pandas as pd
x_df=pd.DataFrame(x)
y_df=pd.DataFrame(y)

In [31]:
x_df.head()

0      1     2     3      4     5      6     7
0  6.0  148.0  72.0  35.0    0.0  33.6  0.627  50.0
1  1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0
2  8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0
3  1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0
4  0.0  137.0  40.0  35.0  168.0  43.1  2.288  33.0

In [34]:
y_df.head()

0
0  1.0
1  0.0
2  1.0
3  0.0
4  1.0

In [35]:
model = Sequential()

In [36]:
model.add(Dense(units=12,input_dim=8,activation='relu'))
model.add(Dense(units=9,activation='relu'))
model.add(Dense(units=1,activation='sigmoid'))

In [38]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [40]:
model.fit(x,y,epochs=150,batch_size=10)

Epoch 1/150
77/77 [==============================] - 4s 4ms/step - loss: 2.4677 - accuracy: 0.6224
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1757 - accuracy: 0.6589
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9991 - accuracy: 0.6589
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9077 - accuracy: 0.6732
Epoch 5/150
77/77 [==============================] - 0s 3ms/step - loss: 0.8505 - accuracy: 0.6719
Epoch 6/150
77/77 [==============================] - 0s 3ms/step - loss: 0.7264 - accuracy: 0.6836
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7283 - accuracy: 0.6771
Epoch 8/150
77/77 [==============================] - 0s 4ms/step - loss: 0.6823 - accuracy: 0.6745
Epoch 9/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6583 - accuracy: 0.6914
Epoch 10/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6475 - accuracy: 0.6888
Epoch 11/

77/77 [==============================] - 0s 3ms/step - loss: 0.5231 - accuracy: 0.7487
Epoch 84/150
77/77 [==============================] - 0s 3ms/step - loss: 0.5385 - accuracy: 0.7240
Epoch 85/150
77/77 [==============================] - 0s 3ms/step - loss: 0.5125 - accuracy: 0.7578
Epoch 86/150
77/77 [==============================] - 0s 3ms/step - loss: 0.5259 - accuracy: 0.7591
Epoch 87/150
77/77 [==============================] - 0s 3ms/step - loss: 0.5434 - accuracy: 0.7539
Epoch 88/150
77/77 [==============================] - 0s 3ms/step - loss: 0.5135 - accuracy: 0.7474
Epoch 89/150
77/77 [==============================] - 0s 3ms/step - loss: 0.5250 - accuracy: 0.7604
Epoch 90/150
77/77 [==============================] - 0s 3ms/step - loss: 0.5443 - accuracy: 0.7487
Epoch 91/150
77/77 [==============================] - 0s 3ms/step - loss: 0.5524 - accuracy: 0.7435
Epoch 92/150
77/77 [==============================] - 0s 3ms/step - loss: 0.5316 - accuracy: 0.7630
Epoch 93/150


In [47]:
loss,accuracy=model.evaluate(x,y)
print(' Accuracy {} \n Loss {}'.format(accuracy,loss))

24/24 [==============================] - 0s 3ms/step - loss: 0.5035 - accuracy: 0.7630
 Accuracy 0.7630208134651184 
 Loss 0.5035180449485779


In [50]:
prediction=model.predict(x)
prediction

24/24 [==============================] - 0s 3ms/step


array([[7.47309864e-01],
       [1.03572488e-01],
       [8.93473923e-01],
       [9.05334428e-02],
       [6.37260199e-01],
       [2.55944341e-01],
       [1.45959541e-01],
       [5.49137950e-01],
       [6.75886214e-01],
       [5.12487665e-02],
       [2.14374349e-01],
       [8.73148561e-01],
       [4.12239432e-01],
       [3.25816013e-02],
       [6.26315475e-01],
       [1.98253930e-01],
       [1.84403643e-01],
       [3.17609906e-01],
       [3.57752144e-01],
       [2.62634397e-01],
       [2.45011792e-01],
       [3.81137580e-01],
       [8.72185469e-01],
       [3.08923841e-01],
       [6.13672554e-01],
       [5.33632696e-01],
       [6.92088842e-01],
       [9.48937237e-02],
       [6.20719314e-01],
       [2.80388594e-01],
       [2.75172234e-01],
       [3.97445917e-01],
       [1.45837352e-01],
       [4.10600379e-02],
       [5.04709482e-01],
       [2.22865924e-01],
       [7.01159060e-01],
       [2.14631125e-01],
       [1.49563193e-01],
       [3.95585567e-01],


In [59]:
rounded_pred=[round(x[0]) for x in prediction]

In [60]:
rounded_pred

[1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,


In [64]:
prediction=((model.predict(x)>(0.5)).astype(int))
prediction

24/24 [==============================] - 0s 2ms/step


array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [74]:
for i in range(len(prediction)):
    print('the actual is {} and predcited is {}'.format(y[i] , prediction[i]))
#     print('%s => expected %d )'%(x[i].tolist(),prediction[i],y[i] ))

the actual is [1.] and predcited is [1]
the actual is [0.] and predcited is [0]
the actual is [1.] and predcited is [1]
the actual is [0.] and predcited is [0]
the actual is [1.] and predcited is [1]
the actual is [0.] and predcited is [0]
the actual is [1.] and predcited is [0]
the actual is [0.] and predcited is [1]
the actual is [1.] and predcited is [1]
the actual is [1.] and predcited is [0]
the actual is [0.] and predcited is [0]
the actual is [1.] and predcited is [1]
the actual is [0.] and predcited is [0]
the actual is [1.] and predcited is [0]
the actual is [1.] and predcited is [1]
the actual is [1.] and predcited is [0]
the actual is [1.] and predcited is [0]
the actual is [1.] and predcited is [0]
the actual is [0.] and predcited is [0]
the actual is [1.] and predcited is [0]
the actual is [0.] and predcited is [0]
the actual is [0.] and predcited is [0]
the actual is [1.] and predcited is [1]
the actual is [1.] and predcited is [0]
the actual is [1.] and predcited is [1]
