In [1]:
import numpy as np
import pandas as pd
import os
import nltk
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train=pd.read_csv('E:/Full Stack Data Scientist Bootcamp/NLP/train.csv')
test=pd.read_csv('E:/Full Stack Data Scientist Bootcamp/NLP/test.csv')

In [3]:
train

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

In [4]:
test

id keyword location  \
0         0     NaN      NaN   
1         2     NaN      NaN   
2         3     NaN      NaN   
3         9     NaN      NaN   
4        11     NaN      NaN   
...     ...     ...      ...   
3258  10861     NaN      NaN   
3259  10865     NaN      NaN   
3260  10868     NaN      NaN   
3261  10874     NaN      NaN   
3262  10875     NaN      NaN   

                                                   text  
0                    Just happened a terrible car crash  
1     Heard about #earthquake is different cities, s...  
2     there is a forest fire at spot pond, geese are...  
3              Apocalypse lighting. #Spokane #wildfires  
4         Typhoon Soudelor kills 28 in China and Taiwan  
...                                                 ...  
3258  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...  
3259  Storm in RI worse than last hurricane. My city...  
3260  Green Line derailment in Chicago http://t.co/U...  
3261  MEG issues Hazardous Weather Outlook (HWO) htt...  
3262  #CityofCalgary has activated its Municipal Eme...  

[3263 rows x 4 columns]

## Text Cleaning 

In [5]:
import re

def remove_url(text):
    url = re.compile(r"https?://\S+|www\.\S+")
    return url.sub(r'', text)


def remove_html(text):
    html=re.compile(r"<.*?>")
    return html.sub(r"",text)                   

In [6]:
import re

def remove_emoji(string):
    emoji_pattern = re.compile(
        "[" 
        u"\U0001F600-\U0001F64F"  # emotions
        u"\U0001F300-\U0001F5FF"  # symbols and pictographs
        u"\U0001F680-\U0001F6FF"  # transport and symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\u2702-\u2780" 
        u"\u24C2-\U0001F251" 
        "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub(r"", string)


In [7]:
# REMOVE THE PUNCTUATION
import string
def remove_punct(text):
    table=str.maketrans("","",string.punctuation)
    return text.translate(table)

In [8]:
train['text']=train.text.map(lambda x: remove_url(x))
train['text']=train.text.map(lambda x: remove_html(x))
train['text']=train.text.map(lambda x: remove_emoji(x))
train['text']=train.text.map(lambda x: remove_punct(x))

In [9]:
# Now the text is clean
train.loc[0, 'text']

'Our Deeds are the Reason of this earthquake May ALLAH Forgive us all'

In [10]:
from nltk.corpus import stopwords
stop=set(stopwords.words('english'))

def remove_stopwords (text):
    text=[word.lower() for word in text.split() if word.lower() not in stop]
    return " ".join(text)

In [11]:
train['text']=train['text'].map(remove_stopwords)

In [12]:
train.text

0            deeds reason earthquake may allah forgive us
1                   forest fire near la ronge sask canada
2       residents asked shelter place notified officer...
3       13000 people receive wildfires evacuation orde...
4       got sent photo ruby alaska smoke wildfires pou...
                              ...                        
7608    two giant cranes holding bridge collapse nearb...
7609    ariaahrary thetawniest control wild fires cali...
7610                      m194 0104 utc5km volcano hawaii
7611    police investigating ebike collided car little...
7612    latest homes razed northern california wildfir...
Name: text, Length: 7613, dtype: object

## Emeddings
### Using Glove

In [13]:
from nltk.tokenize import word_tokenize
import nltk

def create_corpus_tk(df):
    corpus=[]
    for text in train['text']:
        words=[word.lower() for word in word_tokenize(text)]
        corpus.append(words)
       
    return corpus

In [14]:
corpus = create_corpus_tk(train)
num_words=len(corpus)
print(num_words)

7613


In [15]:
corpus

[['deeds', 'reason', 'earthquake', 'may', 'allah', 'forgive', 'us'],
 ['forest', 'fire', 'near', 'la', 'ronge', 'sask', 'canada'],
 ['residents',
  'asked',
  'shelter',
  'place',
  'notified',
  'officers',
  'evacuation',
  'shelter',
  'place',
  'orders',
  'expected'],
 ['13000',
  'people',
  'receive',
  'wildfires',
  'evacuation',
  'orders',
  'california'],
 ['got',
  'sent',
  'photo',
  'ruby',
  'alaska',
  'smoke',
  'wildfires',
  'pours',
  'school'],
 ['rockyfire',
  'update',
  'california',
  'hwy',
  '20',
  'closed',
  'directions',
  'due',
  'lake',
  'county',
  'fire',
  'cafire',
  'wildfires'],
 ['flood',
  'disaster',
  'heavy',
  'rain',
  'causes',
  'flash',
  'flooding',
  'streets',
  'manitou',
  'colorado',
  'springs',
  'areas'],
 ['im', 'top', 'hill', 'see', 'fire', 'woods'],
 ['theres',
  'emergency',
  'evacuation',
  'happening',
  'building',
  'across',
  'street'],
 ['im', 'afraid', 'tornado', 'coming', 'area'],
 ['three', 'people', 'died',

In [16]:
corpus[0]

['deeds', 'reason', 'earthquake', 'may', 'allah', 'forgive', 'us']

In [17]:
len(corpus),len(train.text), num_words

(7613, 7613, 7613)

##### train/test split()

In [18]:
train.text[500:]

500     christian attacked muslims temple mount waving...
501     envw98 nickcocofree juliedicaro jdabe80 worst ...
502     kelly osbourne attacked racist donald trump re...
503     eunicenjoki aiii needs chill answer calmly lik...
504     christian attacked muslims temple mount waving...
                              ...                        
7608    two giant cranes holding bridge collapse nearb...
7609    ariaahrary thetawniest control wild fires cali...
7610                      m194 0104 utc5km volcano hawaii
7611    police investigating ebike collided car little...
7612    latest homes razed northern california wildfir...
Name: text, Length: 7113, dtype: object

In [19]:
train_size=int (train.shape[0] * 0.8)
train_size

6090

In [20]:
train_sentences= train.text[:train_size]
train_labels= train.target[:train_size]

test_sentences = train.text[train_size:]
test_labels = train.target[train_size:]

In [21]:
train_sentences 

0            deeds reason earthquake may allah forgive us
1                   forest fire near la ronge sask canada
2       residents asked shelter place notified officer...
3       13000 people receive wildfires evacuation orde...
4       got sent photo ruby alaska smoke wildfires pou...
                              ...                        
6085            feel like sinking low selfimage take quiz
6086             years afloat pension plans start sinking
6087              feel like sinking unhappiness take quiz
6088    sinking music video tv career brooke hogan tha...
6089    supernovalester feel bad literally feel feelin...
Name: text, Length: 6090, dtype: object

In [22]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


max_len=50

In [23]:
tokenizer=Tokenizer(num_words = num_words)

tokenizer.fit_on_texts(train_sentences)

In [24]:
train_sequences=tokenizer.texts_to_sequences(train_sentences)

In [25]:
train_sequences

[[3739, 696, 235, 41, 1282, 3740, 14],
 [71, 3, 129, 576, 5670, 5671, 1283],
 [1448, 1186, 1882, 495, 5672, 1449, 116, 1882, 495, 976, 1187],
 [2243, 8, 3741, 1070, 116, 976, 24],
 [27, 1071, 358, 5673, 1635, 892, 1070, 5674, 91],
 [2244, 359, 24, 1188, 550, 609, 5675, 373, 1072, 374, 3, 5676, 1070],
 [99, 16, 610, 296, 977, 643, 117, 1636, 5677, 748, 1883, 1284],
 [4, 127, 2245, 36, 3, 5678],
 [236, 11, 116, 893, 432, 697, 577],
 [4, 2246, 2247, 180, 335],
 [520, 8, 395, 156, 297, 411],
 [749,
  470,
  2248,
  138,
  2249,
  2813,
  521,
  611,
  188,
  470,
  2248,
  189,
  189,
  5679,
  117],
 [2814, 117, 1884, 5680, 2248, 1285, 1450, 522, 256, 644, 2815],
 [99, 3742, 612, 1451, 3742],
 [111, 91, 336, 3743, 3744, 52, 22, 312],
 [433, 26],
 [42, 5681],
 [237, 1286],
 [52, 698],
 [5682],
 [2816],
 [894, 396],
 [42, 5683],
 [3745, 29],
 [5684],
 [5685, 46, 1885, 132],
 [1073, 58, 360],
 [42, 1886],
 [5686],
 [1, 3746],
 [257],
 [5687, 2250, 2817, 375],
 [157, 613, 750, 610, 895, 44],


In [26]:
train_padded=pad_sequences(
    train_sequences,maxlen=max_len,truncating='post',padding='post'
)

In [27]:
train_padded

array([[3739,  696,  235, ...,    0,    0,    0],
       [  71,    3,  129, ...,    0,    0,    0],
       [1448, 1186, 1882, ...,    0,    0,    0],
       ...,
       [ 151,    1, 1256, ...,    0,    0,    0],
       [1256,  448,   15, ...,    0,    0,    0],
       [ 151,  204,  539, ...,    0,    0,    0]])

In [28]:
test_sequences=tokenizer.texts_to_sequences(test_sentences)
test_padded=pad_sequences(
    test_sequences,maxlen=max_len,truncating='post',padding='post'
)

In [29]:
test_sequences

[[651, 1256, 698, 122, 525, 723, 859, 670],
 [379, 1256, 819, 78, 403, 443, 33],
 [1303, 52, 1256, 2056, 1168],
 [12, 1256, 4349, 2596],
 [379, 1256, 819, 78, 403, 443, 33],
 [80, 1388, 1061, 898, 174, 920, 1256],
 [4112],
 [379, 1256, 819, 78, 403, 443, 33],
 [92, 644, 897, 92, 1256, 1, 3199, 2990],
 [7607, 3145, 1256, 3968, 1227, 3283, 515, 87, 754, 134],
 [1679, 3579, 268, 1256, 307, 1272, 884, 1726],
 [1028, 1256, 992],
 [1256, 992, 1643, 3562, 3199],
 [379, 1256, 819, 78, 403, 443, 33],
 [533, 1724, 2451, 66, 2764, 302, 1256],
 [644, 2, 897, 1256, 1, 3199, 2990],
 [236, 740, 5, 1256, 992, 46, 101],
 [753, 2563, 2458, 2213, 248, 2458, 1256],
 [151, 1, 1256, 734, 1174, 82, 797],
 [9, 724, 1488, 5436, 1589, 1256, 7101],
 [894, 1975, 1256],
 [1256, 2462, 3718],
 [619, 36, 195, 1457, 4, 1256, 4, 1256, 319, 10, 825, 278, 1355, 36, 87],
 [379, 1256, 819, 78, 403, 443, 33],
 [4, 1256, 1470, 1365, 935, 780, 551, 42, 1801, 1807],
 [1256, 4821, 438, 66, 624, 188, 1756, 1654, 72, 766],
 [1256

In [30]:
test_padded[0],test_padded 

(array([ 651, 1256,  698,  122,  525,  723,  859,  670,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0]),
 array([[ 651, 1256,  698, ...,    0,    0,    0],
        [ 379, 1256,  819, ...,    0,    0,    0],
        [1303,   52, 1256, ...,    0,    0,    0],
        ...,
        [5048,    0,    0, ...,    0,    0,    0],
        [  21,  830, 4532, ...,    0,    0,    0],
        [ 102,   98,  357, ...,    0,    0,    0]]))

In [31]:
len(test_padded)

1523

In [32]:
print(train.text[0])
print(train_sequences[0])

deeds reason earthquake may allah forgive us
[3739, 696, 235, 41, 1282, 3740, 14]


In [33]:
word_index=tokenizer.word_index
word_index

{'like': 1,
 'amp': 2,
 'fire': 3,
 'im': 4,
 'get': 5,
 'via': 6,
 'new': 7,
 'people': 8,
 'news': 9,
 'dont': 10,
 'emergency': 11,
 'one': 12,
 '2': 13,
 'us': 14,
 'video': 15,
 'disaster': 16,
 'burning': 17,
 'body': 18,
 'would': 19,
 'buildings': 20,
 'police': 21,
 'crash': 22,
 'first': 23,
 'california': 24,
 'still': 25,
 'man': 26,
 'got': 27,
 'know': 28,
 'day': 29,
 'back': 30,
 'going': 31,
 'two': 32,
 'time': 33,
 'full': 34,
 'accident': 35,
 'see': 36,
 'world': 37,
 'attack': 38,
 'nuclear': 39,
 'youtube': 40,
 'may': 41,
 'love': 42,
 'go': 43,
 'rt': 44,
 'many': 45,
 'cant': 46,
 '3': 47,
 'watch': 48,
 'collapse': 49,
 'dead': 50,
 'today': 51,
 'car': 52,
 'mass': 53,
 'want': 54,
 'years': 55,
 'work': 56,
 'train': 57,
 'last': 58,
 'good': 59,
 'think': 60,
 'families': 61,
 'hiroshima': 62,
 'life': 63,
 'fires': 64,
 'best': 65,
 'could': 66,
 'say': 67,
 'u': 68,
 'death': 69,
 'hot': 70,
 'forest': 71,
 'way': 72,
 'killed': 73,
 'need': 74,
 'legion

In [34]:
len(tokenizer.index_word)

15470

In [35]:
word_index['reason']

696

###### Creating the Enbedding Dictionary

In [38]:
embedding_dict={}
with open('E:/Full Stack Data Scientist Bootcamp/NLP/archive (2)/glove.twitter.27B.100d.txt','r', encoding='utf-8') as f:
#with open('E:/Full Stack Data Scientist Bootcamp/NLP/archive (2)/glove.twitter.27B.100d.txt','r') as f:
    for line in f:
        values=line.split()
        word=values[0]
        vectors=np.asarray(values[1:],"float32")
        embedding_dict[word]=vectors
        
       

    
f.close()


In [39]:
embedding_dict

{'<user>': array([ 0.63006  ,  0.65177  ,  0.25545  ,  0.018593 ,  0.043094 ,
         0.047194 ,  0.23218  ,  0.11613  ,  0.17371  ,  0.40487  ,
         0.022524 , -0.076731 , -2.2911   ,  0.094127 ,  0.43293  ,
         0.041801 ,  0.063175 , -0.64486  , -0.43657  ,  0.024114 ,
        -0.082989 ,  0.21686  , -0.13462  , -0.22336  ,  0.39436  ,
        -2.1724   , -0.39544  ,  0.16536  ,  0.39438  , -0.35182  ,
        -0.14996  ,  0.10502  , -0.45937  ,  0.27729  ,  0.8924   ,
        -0.042313 , -0.009345 ,  0.55017  ,  0.095521 ,  0.070504 ,
        -1.1781   ,  0.013723 ,  0.17742  ,  0.74142  ,  0.17716  ,
         0.038468 , -0.31684  ,  0.08941  ,  0.20557  , -0.34328  ,
        -0.64303  , -0.878    , -0.16293  , -0.055925 ,  0.33898  ,
         0.60664  , -0.2774   ,  0.33626  ,  0.21603  , -0.11051  ,
         0.0058673, -0.64757  , -0.068222 , -0.77414  ,  0.13911  ,
        -0.15851  , -0.61885  , -0.10192  , -0.47     ,  0.19787  ,
         0.42175  , -0.18458  ,  0.080

In [41]:
num_words=len(word_index) + 1

embedding_matrix=np.zeros((num_words,100))

for word,i in word_index.items():
    if i< num_words:
        emb_vec = embedding_dict.get(word)
        if emb_vec is not None:
            embedding_matrix[i]=emb_vec
            
    

In [57]:
embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.21063   , -0.010992  , -0.17552   , ..., -0.37547001,
         0.58029002,  0.16067   ],
       [ 0.1172    ,  0.0049642 ,  0.011703  , ..., -0.68340999,
        -0.64977998,  0.50405997],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.11549   ,  0.18143   ,  0.39983001, ..., -0.064044  ,
         0.49972001,  0.20979001]])

In [43]:
embedding_matrix.shape

(15471, 100)

In [44]:
word_index['reason']

696

In [45]:
embedding_dict.get('reason')

array([ 3.0746e-01, -8.2411e-02,  1.5418e-01,  4.2281e-01,  9.0060e-02,
        2.7961e-01,  7.4148e-01,  9.7240e-02, -3.6680e-01,  4.2645e-01,
        3.1740e-01, -9.6437e-01, -4.5333e+00, -1.2831e-01, -2.2068e-01,
        3.2468e-01, -1.2633e-02, -1.6605e-01,  3.6976e-01, -3.1943e-01,
        3.4408e-01,  4.4734e-01, -1.7704e-01,  2.6574e-01,  4.5964e-01,
        4.9419e-01,  2.1887e-01,  4.0049e-02, -2.1725e-01,  3.9388e-02,
        8.6184e-02, -4.9555e-01, -3.9347e-01, -4.6257e-02, -3.0383e-01,
        2.8341e-01, -3.0416e-01,  5.1533e-02, -7.8039e-02,  2.7330e-01,
       -1.4775e-01,  6.0520e-01, -3.6645e-03, -4.3473e-01, -4.5780e-01,
       -2.4630e-01,  3.5619e-01, -4.4311e-02, -1.0088e-01,  4.6684e-01,
       -3.4813e-01,  6.2534e-01, -1.2708e-02, -3.5268e-01,  1.8414e-01,
        3.0383e-01, -4.8866e-01,  1.4554e-01,  9.8332e-02, -6.8324e-02,
        1.0610e-01, -2.8812e-02, -1.6139e-01,  5.5888e-04, -6.8000e-02,
        1.1909e-01,  3.8607e-01,  2.5173e-01, -4.5272e-01,  3.27

In [47]:
(embedding_matrix[696] == embedding_dict.get('reason')).all()

True

In [48]:
print(train_padded.shape)
print(train_labels.shape)


(6090, 50)
(6090,)


In [49]:
print(test_padded.shape)
print(test_labels.shape)

(1523, 50)
(1523,)


### Beaseline Model with GloVe

In [52]:
from keras.models import Sequential
from keras.layers import Embedding ,LSTM,Dense,Dropout
from keras.initializers import Constant
from keras.optimizers import Adam

In [55]:
model=Sequential()

model.add(Embedding(num_words,100,embeddings_initializer=Constant(embedding_matrix),input_length=max_len,trainable=False))

model.add(LSTM(100,dropout=0.1))

model.add(Dense(1,activation='sigmoid'))

optimizer=Adam(learning_rate=3e-4)

model.compile(loss='binary_crossentropy',optimizer=optimizer,metrics=['accuracy'])


In [56]:
history=model.fit(
train_padded,
train_labels,
epochs=20,
validation_data=(test_padded,test_labels),
verbose=1    
)

Epoch 1/20
191/191 [==============================] - 30s 91ms/step - loss: 0.5370 - accuracy: 0.7271 - val_loss: 0.4422 - val_accuracy: 0.8050
Epoch 2/20
191/191 [==============================] - 15s 79ms/step - loss: 0.4622 - accuracy: 0.7939 - val_loss: 0.4280 - val_accuracy: 0.8089
Epoch 3/20
191/191 [==============================] - 15s 78ms/step - loss: 0.4435 - accuracy: 0.8095 - val_loss: 0.4325 - val_accuracy: 0.8070
Epoch 4/20
191/191 [==============================] - 15s 77ms/step - loss: 0.4388 - accuracy: 0.8089 - val_loss: 0.4286 - val_accuracy: 0.8122
Epoch 5/20
191/191 [==============================] - 15s 80ms/step - loss: 0.4285 - accuracy: 0.8176 - val_loss: 0.4357 - val_accuracy: 0.7984
Epoch 6/20
191/191 [==============================] - 16s 81ms/step - loss: 0.4231 - accuracy: 0.8207 - val_loss: 0.4213 - val_accuracy: 0.8056
Epoch 7/20
191/191 [==============================] - 15s 76ms/step - loss: 0.4099 - accuracy: 0.8220 - val_loss: 0.4372 - val_accuracy:

In [58]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 100)           1547100   
                                                                 
 lstm (LSTM)                 (None, 100)               80400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 1,627,601
Trainable params: 80,501
Non-trainable params: 1,547,100
_________________________________________________________________


In [59]:
sequences=tokenizer.texts_to_sequences(test.text)
padded=pad_sequences(sequences,maxlen=max_len, padding ='post',truncating='post')

In [60]:
history=model.fit(
    train_padded, train_labels, epochs=20, validation_data=(test_padded,test_labels)
)

Epoch 1/20
191/191 [==============================] - 16s 86ms/step - loss: 0.2996 - accuracy: 0.8801 - val_loss: 0.5114 - val_accuracy: 0.7787
Epoch 2/20
191/191 [==============================] - 14s 73ms/step - loss: 0.2975 - accuracy: 0.8795 - val_loss: 0.5166 - val_accuracy: 0.7728
Epoch 3/20
191/191 [==============================] - 16s 83ms/step - loss: 0.2848 - accuracy: 0.8867 - val_loss: 0.4836 - val_accuracy: 0.7879
Epoch 4/20
191/191 [==============================] - 18s 92ms/step - loss: 0.2746 - accuracy: 0.8936 - val_loss: 0.4995 - val_accuracy: 0.7965
Epoch 5/20
191/191 [==============================] - 18s 93ms/step - loss: 0.2733 - accuracy: 0.8908 - val_loss: 0.4890 - val_accuracy: 0.7991
Epoch 6/20
191/191 [==============================] - 16s 84ms/step - loss: 0.2649 - accuracy: 0.8961 - val_loss: 0.5492 - val_accuracy: 0.7833
Epoch 7/20
191/191 [==============================] - 15s 77ms/step - loss: 0.2597 - accuracy: 0.9013 - val_loss: 0.5380 - val_accuracy:

In [67]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 100)           1547100   
                                                                 
 lstm (LSTM)                 (None, 100)               80400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 1,627,601
Trainable params: 80,501
Non-trainable params: 1,547,100
_________________________________________________________________


In [61]:
sequences

[[708, 1653, 52, 22],
 [363, 235, 952, 3140, 484, 2085, 172],
 [71, 3, 786, 2811, 4252, 697, 577, 1084, 223],
 [303, 4323, 6220, 1070],
 [1812, 2134, 813, 4374, 835, 3381],
 [235],
 [517, 25, 342, 63, 2527, 1496, 2908, 2908],
 [584],
 [1010, 546],
 [385],
 [1, 935],
 [],
 [471],
 [],
 [751],
 [5323, 2250, 306, 375, 1047, 9, 3, 3059, 2250, 306, 5843, 1390],
 [3755, 3242, 375],
 [510, 2344, 801, 323, 375, 5843, 1390],
 [171, 5843, 1390, 5843, 1390, 5843, 1390, 5843, 1390, 2819],
 [4802, 2690, 826, 375, 1390, 826, 375],
 [3650, 37, 375, 2],
 [17, 26, 375, 5843, 1390, 6],
 [2455, 408, 8, 82, 93, 440, 317, 1369, 672, 680, 13, 139, 299, 375, 7461],
 [2949,
  991,
  900,
  2344,
  375,
  902,
  103,
  466,
  320,
  395,
  1116,
  154,
  139,
  5843,
  1390],
 [980, 375, 5843, 1390],
 [650, 1789, 241, 139, 375, 29, 86, 365, 887],
 [651, 375, 109, 859, 5843, 1390],
 [195, 113, 4214, 4405, 599, 770, 1136, 2, 2344, 375, 5843, 1390, 5167],
 [3300, 619, 375, 3372],
 [35, 3314, 2581, 1285, 3579, 30,

In [68]:
padded

array([[ 708, 1653,   52, ...,    0,    0,    0],
       [ 363,  235,  952, ...,    0,    0,    0],
       [  71,    3,  786, ...,    0,    0,    0],
       ...,
       [ 724,  516,  168, ...,    0,    0,    0],
       [5410,  455,  249, ...,    0,    0,    0],
       [5102, 2192, 1180, ...,    0,    0,    0]])

In [62]:
pred=model.predict(padded)
pred_int=pred.round().astype('int')

102/102 [==============================] - 4s 26ms/step


In [63]:
pred

array([[0.99452865],
       [0.9940383 ],
       [0.992805  ],
       ...,
       [0.99558014],
       [0.67778313],
       [0.987649  ]], dtype=float32)

In [64]:
padded[5]

array([235,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0])

In [66]:
pred_int

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [69]:
model.predict(padded[5].reshape(1,-1))

1/1 [==============================] - 0s 413ms/step


array([[0.9924016]], dtype=float32)

In [71]:
# Check inverse
reverse_word_index=dict([(value,key) for (key,value) in word_index.items()])
def decode(text):
    return " ".join([reverse_word_index.get(i,'?') for i in text])

In [73]:
decode(sequences[5])

'earthquake'