In [1]:
import numpy as np
x=np.arange(1,29).reshape(14,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28]])

In [28]:
a=[1,0,0,1,0,1,1,1,0,0,1,0,0,1]
y=np.array(a)
y

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1])

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y)

In [29]:
x_train

array([[ 4],
       [ 2],
       [ 5],
       [14],
       [ 9],
       [ 7],
       [16],
       [11],
       [ 3],
       [ 0],
       [15],
       [12]])

In [30]:
x_test

array([[18],
       [ 1],
       [19],
       [ 8],
       [10],
       [17],
       [ 6],
       [13]])

In [31]:
y_train

array([ 9, 12, 29, 89, 53, 40, 89, 62, 11, 15, 84, 68])

In [32]:
y_test

array([ 99,   5, 106,  51,  74, 101,  23,  73])

In [33]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=8,random_state=100)

In [34]:
x_test

array([[23, 24],
       [25, 26],
       [11, 12],
       [ 3,  4],
       [19, 20],
       [ 9, 10],
       [13, 14],
       [ 5,  6]])

In [35]:
x_train

array([[ 1,  2],
       [21, 22],
       [15, 16],
       [ 7,  8],
       [27, 28],
       [17, 18]])

In [36]:
y_test

array([0, 0, 1, 0, 0, 0, 1, 0])

In [37]:
y_train

array([1, 1, 1, 1, 1, 0])

In [20]:
# LAB work Strat
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split



In [21]:
x=np.arange(20).reshape(-1,1)
y=np.array([15,5,12,11,9,29,23,40,51,53,74,62,68,73,89,84,89,101,99,106])

In [22]:
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [23]:
y

array([ 15,   5,  12,  11,   9,  29,  23,  40,  51,  53,  74,  62,  68,
        73,  89,  84,  89, 101,  99, 106])

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=8,random_state=0)

In [25]:
x_train

array([[ 4],
       [ 2],
       [ 5],
       [14],
       [ 9],
       [ 7],
       [16],
       [11],
       [ 3],
       [ 0],
       [15],
       [12]])

In [26]:
x_test

array([[18],
       [ 1],
       [19],
       [ 8],
       [10],
       [17],
       [ 6],
       [13]])

In [27]:
y_train

array([ 9, 12, 29, 89, 53, 40, 89, 62, 11, 15, 84, 68])

In [76]:
y_test

array([ 99,   5, 106,  51,  74, 101,  23,  73])

In [99]:
import pandas as pd
x_train_dataframe=pd.DataFrame(x_train,columns=['X-train'])
x_train_dataframe

X-train
0         4
1         2
2         5
3        14
4         9
5         7
6        16
7        11
8         3
9         0
10       15
11       12

In [101]:
y_train_dataframe=pd.DataFrame(y_train,columns=['Y-train'])
y_train_dataframe

Y-train
0         9
1        12
2        29
3        89
4        53
5        40
6        89
7        62
8        11
9        15
10       84
11       68

In [102]:
x_test_dataframe=pd.DataFrame(x_test,columns=['X-test'])
x_test_dataframe

X-test
0      18
1       1
2      19
3       8
4      10
5      17
6       6
7      13

In [103]:
y_test_dataframe=pd.DataFrame(y_test,columns=['Y-test'])
y_test_dataframe

Y-test
0      99
1       5
2     106
3      51
4      74
5     101
6      23
7      73

In [104]:
xy_train_dataframe=pd.concat([x_train_dataframe,y_train_dataframe],axis=1)
xy_train_dataframe

X-train  Y-train
0         4        9
1         2       12
2         5       29
3        14       89
4         9       53
5         7       40
6        16       89
7        11       62
8         3       11
9         0       15
10       15       84
11       12       68

In [105]:
#Making the object of LinearRegression class
model=LinearRegression()


In [106]:
#Train the model by the part of test-data  with the original (input and output) data 
model.fit(x_train,y_train)

LinearRegression()

In [107]:
# the values of c or y intercept 
model.intercept_

0.5711361310132901

In [108]:
# the vlaue of m or slop 
model.coef_

array([5.65455476])

In [109]:
# determination of R^2 for both data (train data)
model.score(x_train,y_train)*100

95.0057032418045

In [110]:
# determination of R^2 for both data (test data)
model.score(x_test,y_test)*100

95.10521048204069

In [111]:
#Now the pridict the y value on the base of the train data by using the nodel.predict function for the x_test data 
y_test_predict=model.predict(x_test)
y_test_predict

array([102.3531218 ,   6.22569089, 108.00767656,  45.80757421,
        57.11668373,  96.69856704,  34.49846469,  74.080348  ])

In [112]:
# original values of Y of the test data 
y_test
# converthing it into the data frame
y_test_original_dataframe=pd.DataFrame(y_test,columns=['Y-original(y-test-original-dataframe)'])
y_test_original_dataframe

Y-original(y-test-original-dataframe)
0                                     99
1                                      5
2                                    106
3                                     51
4                                     74
5                                    101
6                                     23
7                                     73

In [113]:
#Making the datafrom of the 'Y-predicted(y-test-predict-dataframe) values
y_test_predict_dataframe=pd.DataFrame(y_test_predict,columns=['Y-predicted(y-test-predict-dataframe)'])
y_test_predict_dataframe

Y-predicted(y-test-predict-dataframe)
0                             102.353122
1                               6.225691
2                             108.007677
3                              45.807574
4                              57.116684
5                              96.698567
6                              34.498465
7                              74.080348

In [114]:
#concating the data frame the of (y_test_original_dataframe, y_test_pradict_datafame)

y_test_original_predict_dataframe=pd.concat([y_test_original_dataframe, y_test_predict_dataframe], axis=1)
y_test_original_predict_dataframe


Y-original(y-test-original-dataframe)  \
0                                     99   
1                                      5   
2                                    106   
3                                     51   
4                                     74   
5                                    101   
6                                     23   
7                                     73   

   Y-predicted(y-test-predict-dataframe)  
0                             102.353122  
1                               6.225691  
2                             108.007677  
3                              45.807574  
4                              57.116684  
5                              96.698567  
6                              34.498465  
7                              74.080348

In [115]:
# conbining the ( original and predicted ) of the etst and train datafame

dataframe=pd.concat([xy_dataframe, y_test_original_predict_dataframe], axis=1)
dataframe

X-train  Y-train  Y-original(y-test-original-dataframe)  \
0         4        9                                   99.0   
1         2       12                                    5.0   
2         5       29                                  106.0   
3        14       89                                   51.0   
4         9       53                                   74.0   
5         7       40                                  101.0   
6        16       89                                   23.0   
7        11       62                                   73.0   
8         3       11                                    NaN   
9         0       15                                    NaN   
10       15       84                                    NaN   
11       12       68                                    NaN   

    Y-predicted(y-test-predict-dataframe)  
0                              102.353122  
1                                6.225691  
2                              108.007677  
3                               45.807574  
4                               57.116684  
5                               96.698567  
6                               34.498465  
7                               74.080348  
8                                     NaN  
9                                     NaN  
10                                    NaN  
11                                    NaN

In [118]:
full_dataframe=pd.concat([dataframe,x_test_dataframe], axis=1)
full_dataframe

X-train  Y-train  Y-original(y-test-original-dataframe)  \
0         4        9                                   99.0   
1         2       12                                    5.0   
2         5       29                                  106.0   
3        14       89                                   51.0   
4         9       53                                   74.0   
5         7       40                                  101.0   
6        16       89                                   23.0   
7        11       62                                   73.0   
8         3       11                                    NaN   
9         0       15                                    NaN   
10       15       84                                    NaN   
11       12       68                                    NaN   

    Y-predicted(y-test-predict-dataframe)  X-test  
0                              102.353122    18.0  
1                                6.225691     1.0  
2                              108.007677    19.0  
3                               45.807574     8.0  
4                               57.116684    10.0  
5                               96.698567    17.0  
6                               34.498465     6.0  
7                               74.080348    13.0  
8                                     NaN     NaN  
9                                     NaN     NaN  
10                                    NaN     NaN  
11                                    NaN     NaN

In [ ]:
# error factor 

In [127]:
from sklearn import metrics
MAE=metrics.mean_absolute_error(y_test_original_dataframe,y_test_predict_dataframe)
MAE

5.692809621289664

In [128]:
import numpy as np
RMSE=np.sqrt(MAE)
RMSE

2.385960942951427