In [1]:
import numpy as np


In [4]:
list=[1,2,3,4,5]
arr=np.array(list)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [22]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr=np.array([list1,list2,list3])

In [23]:
arr.shape

(3, 3)

In [24]:
arr[1][2]

6

In [26]:
arr[2][2]=300

In [27]:
arr

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8, 300]])

In [80]:
arr[arr[:,:]>5]

array([  6,   7,   8, 300])

In [93]:
arr[:-2,:-2]

array([[1]])

In [94]:
arr[:2,2:]

array([[3],
       [6]])

## Pandas 

In [95]:
import pandas as pd


In [97]:
# columnname, rowindex[loc] ,rowindex columnindex number[iloc]

In [105]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
df=pd.DataFrame(data=np.arange(0,15).reshape(3,5),index=['row1','row2','row3'],columns=['col1','col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14

In [118]:
df.iloc[1:,1:]

col2  col3  col4  col5
row2     6     7     8     9
row3    11    12    13    14

In [128]:
df.loc[['row1','row3']]

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row3    10    11    12    13    14

In [129]:
df[['col1','col3']]

col1  col3
row1     0     2
row2     5     7
row3    10    12

In [137]:
df.loc[:]

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14

In [152]:
df.iloc[:,-1:]

col5
row1     4
row2     9
row3    14

In [176]:
df.iloc[:,:-1]

col1  col2  col3  col4
row1     0     1     2     3
row2     5     6     7     8
row3    10    11    12    13

In [179]:
df.iloc[2,3]=np.NaN

In [180]:
df

col1  col2  col3  col4  col5
row1     0     1     2   3.0     4
row2     5     6     7   8.0     9
row3    10    11    12   NaN    14

In [184]:
df[df.iloc[:]<8]='Q'

In [185]:
df

col1 col2 col3 col4 col5
row1    Q    Q    Q    Q    Q
row2    Q    Q    Q  8.0    9
row3   10   11   12  NaN   14

In [193]:
from io import StringIO

data=('a,b,c,d\n'
    '1,2,3,4\n'
     'a,b,c,d\n'
     'r,s,t,u\n'
    )

In [199]:
df=pd.read_csv(StringIO(data),dtype='object')

In [200]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       3 non-null      object
dtypes: object(4)
memory usage: 224.0+ bytes


In [217]:
from io import StringIO

data=('a,b,c,d\n'
    '1,2,3,e\n'
     'a,5,c,d\n'
     'r,7,t,u\n'
    )

In [218]:
df=pd.read_csv(StringIO(data),dtype={'b':int})

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   a       3 non-null      object
 1   b       3 non-null      int32 
 2   c       3 non-null      object
 3   d       3 non-null      object
dtypes: int32(1), object(3)
memory usage: 212.0+ bytes


In [220]:
from io import StringIO

data=('a,b,c,d\n'
    '1,2,3,e\n'
     'a,5,c,d\n'
     'r,7,t,u\n'
    )

In [221]:
df=pd.read_csv(StringIO(data))
df

a  b  c  d
0  1  2  3  e
1  a  5  c  d
2  r  7  t  u

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   a       3 non-null      object
 1   b       3 non-null      int64 
 2   c       3 non-null      object
 3   d       3 non-null      object
dtypes: int64(1), object(3)
memory usage: 224.0+ bytes


In [232]:
from io import StringIO

data=('title,col1,col2,col3\n'
    '1sd,2za,3,e\n'
     'a,5,c,d\n'
     'rrr,7,tsd,u\n'
    )

In [233]:
df=pd.read_csv(StringIO(data),usecols=['title','col2','col3'],index_col='col3')
df

title col2
col3           
e      1sd    3
d        a    c
u      rrr  tsd

In [234]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, e to u
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   title   3 non-null      object
 1   col2    3 non-null      object
dtypes: object(2)
memory usage: 72.0+ bytes


In [239]:
df=pd.read_csv(StringIO(data),index_col=2)
df

title col1 col3
col2                
3      1sd  2za    e
c        a    5    d
tsd    rrr    7    u

In [240]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 3 to tsd
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   title   3 non-null      object
 1   col1    3 non-null      object
 2   col3    3 non-null      object
dtypes: object(3)
memory usage: 96.0+ bytes


In [ ]:
from io import StringIO

data=('title,col1,col2,col3\n'
    '1sd,2za,3,e\n'
     'a,5,c,d\n'
     'rrr,7,tsd,u\n'
    )

In [244]:
df=pd.read_csv(StringIO(data),usecols=['col1','col2','col3'],index_col=0)
df

col2 col3
col1          
2za     3    e
5       c    d
7     tsd    u

In [246]:
from io import StringIO

data=('title-col1-col2-col3\n'
    '1sd-2za-3-e\n'
     'a-5-c-d\n'
     'rrr-7-tsd-u\n'
    )

In [247]:
df=pd.read_csv(StringIO(data),usecols=['col1','col2','col3'],index_col=0,sep='-')
df

col2 col3
col1          
2za     3    e
5       c    d
7     tsd    u