In [4]:
import numpy as  np
a=[1,2,3,4,5,6]
myarr=np.array(a)

n=int(input("enter the length of array :"))
for i in range(n):
    myarr[i]=int(input("enter the value in myarry[" + str(i) +"] :"))
    
    
myarr    

enter the length of array :6
enter the value in myarry[0] :11
enter the value in myarry[1] :12
enter the value in myarry[2] :13
enter the value in myarry[3] :14
enter the value in myarry[4] :15
enter the value in myarry[5] :16


array([11, 12, 13, 14, 15, 16])

In [5]:
del myarr



In [18]:
l=[]


n=int(input("enter the size of list:"))
for i in range(n):
    a=int(input("enter the element in the {}:".format(i)))
    l.append(a)
  
arr=np.array(l)
arr[5:9]

enter the size of list:11
enter the element in the 0:0
enter the element in the 1:1
enter the element in the 2:2
enter the element in the 3:3
enter the element in the 4:4
enter the element in the 5:5
enter the element in the 6:6
enter the element in the 7:7
enter the element in the 8:8
enter the element in the 9:9
enter the element in the 10:10


array([5, 6, 7, 8])

# import numpy as np

rows=int(input("enter number of rows:"))

cols=int(input("enter the number of column"))

a=[[],[]]
myarray=np.array

In [32]:
import numpy as np
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [41]:
import numpy as np
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [39]:
import numpy as np
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
import numpy as np
a=np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
import numpy as np
a=np.diag([5,6,7,4,3])
a

array([[5, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 3]])

In [45]:
import numpy as np
b=np.diag(a)
b

array([5, 6, 7, 4, 3])

In [87]:
import numpy as np
a=np.random.randint(1,4)
a

3

In [90]:
import numpy as np
a=np.random.randint(1,2,(1,4))
a

array([[1, 1, 1, 1]])

In [109]:
import numpy as np
a=np.random.rand(3)
a

array([0.62280307, 0.85430323, 0.63377864])

In [121]:
import numpy as np
a=np.random.rand(3,5)
a

array([[0.08726522, 0.42936585, 0.24677145, 0.93716598, 0.28186197],
       [0.28486635, 0.67638071, 0.42012846, 0.75321407, 0.07638199],
       [0.39467987, 0.06795345, 0.85256299, 0.94043961, 0.17937681]])

In [108]:
import numpy as np
a=np.random.randint(1,7,4)
a

array([1, 6, 6, 1])

In [119]:
import numpy as np
a=np.random.randn(5,5,3)
a

array([[[ 1.07609478e-02, -3.72008768e-01,  1.02705948e+00],
        [ 6.41420712e-01, -2.99921179e-01,  9.60923353e-02],
        [-7.13644971e-01,  1.62587925e+00, -1.02792959e+00],
        [-2.32659382e+00, -3.14215038e-01, -1.04181567e-01],
        [ 3.93721675e-01, -4.12586389e-01,  1.11461594e+00]],

       [[-5.00161773e-01, -8.14339722e-02,  1.01427165e+00],
        [ 1.39154279e-01, -2.71787769e-01, -8.51918204e-01],
        [ 1.90377766e-01,  9.91689763e-01,  4.70246611e-01],
        [-1.09960119e+00,  3.35319280e-01, -6.61989424e-01],
        [ 4.95623857e-01, -1.50027034e+00,  3.43437632e-01]],

       [[-2.31125661e-01,  1.22943180e+00,  6.84711773e-01],
        [ 1.30178930e-01, -2.07358558e+00, -9.64592120e-01],
        [-9.15777404e-01, -1.36911095e+00,  1.04796752e-01],
        [-5.60753690e-02, -2.76085782e-01, -1.05603269e-01],
        [-2.02056843e-01, -3.92222693e-01, -1.60156552e-01]],

       [[-1.02941541e-01,  2.98144732e-01, -1.30883242e+00],
        [ 5.115223

array([[[ 1.07609478e-02, -3.72008768e-01,  1.02705948e+00],
        [ 6.41420712e-01, -2.99921179e-01,  9.60923353e-02],
        [-7.13644971e-01,  1.62587925e+00, -1.02792959e+00],
        [-2.32659382e+00, -3.14215038e-01, -1.04181567e-01],
        [ 3.93721675e-01, -4.12586389e-01,  1.11461594e+00]],

       [[-5.00161773e-01, -8.14339722e-02,  1.01427165e+00],
        [ 1.39154279e-01, -2.71787769e-01, -8.51918204e-01],
        [ 1.90377766e-01,  9.91689763e-01,  4.70246611e-01],
        [-1.09960119e+00,  3.35319280e-01, -6.61989424e-01],
        [ 4.95623857e-01, -1.50027034e+00,  3.43437632e-01]],

       [[-2.31125661e-01,  1.22943180e+00,  6.84711773e-01],
        [ 1.30178930e-01, -2.07358558e+00, -9.64592120e-01],
        [-9.15777404e-01, -1.36911095e+00,  1.04796752e-01],
        [-5.60753690e-02, -2.76085782e-01, -1.05603269e-01],
        [-2.02056843e-01, -3.92222693e-01, -1.60156552e-01]],

       [[-1.02941541e-01,  2.98144732e-01, -1.30883242e+00],
        [ 5.115223

In [124]:
import numpy as np
c=np.random.randint(1,100,5)
c

array([28, 31, 43, 13, 11])

In [152]:
for i in range(c.size):
    print(str(i),end=" -> ")
    print(c[i])

0 -> 28
1 -> 31
2 -> 43
3 -> 13
4 -> 11


In [158]:
c[-17:]

array([28, 31, 43, 13, 11])

In [160]:
import numpy as np
a=np.random.randint(1,15,20)
a

array([ 2, 11, 13,  5, 11,  9, 13,  9, 14, 10, 14,  7,  4, 12, 13,  1, 13,
        4,  9, 11])

In [175]:
a.resize((4,5))
a

array([[ 2, 11, 13,  5, 11],
       [ 9, 13,  9, 14, 10],
       [14,  7,  4, 12, 13],
       [ 1, 13,  4,  9, 11]])

In [176]:
a=a.reshape((2,10))

In [177]:
a

array([[ 2, 11, 13,  5, 11,  9, 13,  9, 14, 10],
       [14,  7,  4, 12, 13,  1, 13,  4,  9, 11]])

In [179]:
a=a.reshape(20)

In [180]:
a

array([ 2, 11, 13,  5, 11,  9, 13,  9, 14, 10, 14,  7,  4, 12, 13,  1, 13,
        4,  9, 11])

In [185]:
a=a.reshape((5,-1))
a

array([[ 2, 11, 13,  5],
       [11,  9, 13,  9],
       [14, 10, 14,  7],
       [ 4, 12, 13,  1],
       [13,  4,  9, 11]])

In [186]:
a.ndim

2

In [188]:
# Seed function is used to fixed the ramdom genrated values by the rand function
import numpy as np
np.random.seed(20)
arr1=np.random.randint(1,100,12)
arr1

array([91, 16, 96, 29, 91, 10, 21, 76, 23, 72, 35, 97])

In [189]:
arr1=np.random.randint(1,100,12)
arr1

array([41, 86, 91, 27, 84, 17, 63, 17,  8, 99,  7, 27])

In [190]:
arr1=np.random.randint(1,100,12)
arr1

array([14, 76, 59, 26,  4, 75, 76, 62, 78, 84, 58, 95])

In [211]:

row=int(input("enter the number of rows"))
col=int(input("enter the number of columns"))

matrix=[]
for i in range(row):
    temp=[]
    for j in range(col):
        print("enter the value at the location of :arr["+ str(i)+"]["+str(j) +"]")
        n=int(input())
        temp.append(n)
        
    print(str(i)+" row completed fill")
    matrix.append(temp)
    
matrix=np.array(matrix) 
#matrix
for i in range(row):
    for j in range(col):
        print(matrix[i,j],end=",")
        print(matrix[i][j],end="     ")
    print()        

enter the number of rows3
enter the number of columns3
enter the value at the location of :arr[0][0]
1
enter the value at the location of :arr[0][1]
2
enter the value at the location of :arr[0][2]
3
0 row completed fill
enter the value at the location of :arr[1][0]
4
enter the value at the location of :arr[1][1]
5
enter the value at the location of :arr[1][2]
6
1 row completed fill
enter the value at the location of :arr[2][0]
7
enter the value at the location of :arr[2][1]
8
enter the value at the location of :arr[2][2]
9
2 row completed fill
1,1     2,2     3,3     
4,4     5,5     6,6     
7,7     8,8     9,9     


In [209]:
type(matrix)

numpy.ndarray

In [212]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [223]:
a=matrix[:2,1:3]
a

array([[2, 3],
       [5, 6]])

In [225]:
a=a*2
a

array([[ 8, 12],
       [20, 24]])

In [226]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [229]:
t1=np.array([10,20,30,40,50,60,70,80])
t2=t1[2:5]
t2[:]=0
t2
t1

array([0, 0, 0])

In [230]:
t1

array([10, 20,  0,  0,  0, 60, 70, 80])

In [231]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [232]:
slicing=matrix[1:,1:]
slicing

array([[5, 6],
       [8, 9]])

In [235]:
slicing=slicing*2
slicing

array([[20, 24],
       [32, 36]])

In [236]:
matrix

array([[ 1,  2,  3],
       [ 4, 10, 12],
       [ 7, 16, 18]])

In [237]:
# by using the copy() the changinh in the slicing part would not reflecting with the orginal array/matrix
# by default mode is view() is used the original would change 

In [248]:
#   view --- by default 

t1=np.array([10,20,30,40,50,60,70,80,90,100])
t2=t1[3:8]
t2[:]=0
t2
t1

array([ 10,  20,  30,   0,   0,   0,   0,   0,  90, 100])

In [251]:
#   view --- by  explixitly 

t1=np.array([10,20,30,40,50,60,70,80,90,100])
t2=t1[3:8].copy()
t2[:]=0
t2
t1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [315]:
import numpy as np
arr1=np.arange(1,15)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [316]:
arr2=arr1[arr1>=6]
arr2

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [317]:
arr2=arr2*2
arr2

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [318]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [319]:
arr2

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [329]:
arr1[arr1%2]=9
arr1

array([ 9,  9,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [356]:
import numpy as np
z=np.arange(1,5)
np.max(z)
np.min(z)
np.argmin(z)
np.argmax(z)
np.sqrt(z)
np.sum(z)
np.cos(z)
np.tan(z)
np.sin(z)
np.log(z)
np.mean(z)
np.median(z)

2.5

In [357]:
np.linspace(1,19,5)

array([ 1. ,  5.5, 10. , 14.5, 19. ])

In [367]:
import numpy as np
x=np.random.randint(1,21,5)
x

array([17, 17,  6, 11,  1])

In [369]:
np.random.shuffle(x)
x

array([ 1, 17, 17, 11,  6])

In [372]:
y=np.unique(x).size
y

4

In [371]:
np.unique(x).size

4

In [389]:
#  ----------( stacking  )--------------
a=np.random.randint(1,100,5)
a

array([61, 32, 71, 47, 41])

In [390]:
b=np.random.randint(1,100,5)
b

array([ 1,  4, 25, 86, 26])

In [391]:
np.hstack((a,b))

array([61, 32, 71, 47, 41,  1,  4, 25, 86, 26])

In [392]:
np.vstack((a,b))

array([[61, 32, 71, 47, 41],
       [ 1,  4, 25, 86, 26]])

In [395]:
np.ones(4)

array([1., 1., 1., 1.])